### ISSUE TITLE
Deprecate MultiJob

### ISSUE THREAD

**Issue by britram** [mami-project/mplane-sdk#13]
Replace MultiJob with the ability for a measure specification to select a subset of a running Job's results based on temporal scope.

**Comment by irl** [comment]
MultiJob is currently broken:

************\* Module mplane.scheduler
E:342,13: Instance of 'MultiJob' has no 'collect_results' member (no-member)

Not looked too far into this yet, but the error shows up in pylint.

**Comment by britram** [comment]
Another reason to nuke it. I think I can probably go ahead and do this in a separate branch and merge back to master (since the file that contains all the processing for it is going to get completely replaced anyway).

**Comment by britram** [comment]
Done in the websockets branch
