### ISSUE TITLE
Exception (in mplane.model) does not inherit from BaseException

### ISSUE THREAD

**Issue by irl** [mami-project/mplane-sdk#17]
If we want to "raise" mplane.model.Exception then we really should inherit from BaseException. If we don't want to raise it and only use this as a message type, then we should remove the code where we raise it.

**Comment by britram** [comment]
> If we don't want to raise it and only use this as a message type

this is the case.

> then we should remove the code where we raise it.

wat

**Comment by irl** [comment]
This does not appear to be a problem in the current master branch, nor in any of the branches.
