### ISSUE TITLE
tests don't cover basic client/component interaction

### ISSUE THREAD

**Issue by britram** [mami-project/mplane-sdk#6]
add a new full-up integration test that runs the `mplane.components.loopback` component via nose. Also expand loopback capability to test all primitive types and both interaction patterns.

**Comment by irl** [comment]
Irrelevant, we do not have mPlane support at this time. Old code is gone. We can add this back later with the mPlane plan.

**Comment by britram** [comment]
this is still an issue with the mplane SDK.

**Comment by irl** [comment]
Oops, thought this was on pathspider. Pruning.

**Comment by britram** [comment]
Folded into #18
