### ISSUE TITLE
Auto-building documentation

### ISSUE THREAD

**Issue by irl** [mami-project/mplane-sdk#8]
If we are going to be maintaining the mplane-sdk as part of MAMI, we may like to make changes in the documentation. It would be helpful to have the changes autobuilt so we can refer to them.

I've started on this at http://mplane-sdk.readthedocs.org/en/latest/ which rebuilds automatically, but still needs the dependencies worked out so it can build correctly.

Once this is working, should we replace links to the documentation to ours throughout the repository, or do we anticipate folding changes back into the original mPlane repository?

I guess the question is, does MAMI become the canonical location for these resources now?

**Comment by britram** [comment]
> I guess the question is, does MAMI become the canonical location for these resources now?
> 
> My opinion: yes. Need to verify that with the rest of the mPlane consortium, which I'll kick off a thread to do shortly.
